version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s \n"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG

root:
  handlers: [ console ]
  level: DEBUG

loggers:
  main:
    level: DEBUG
    handlers: [ console ]
    qualname: main
    propagate: false
  Scrapper:
    level: DEBUG
    handlers: [ console ]
    qualname: Scrapper
    propagate: false
  CsvDataService:
    level: DEBUG
    handlers: [ console ]
    qualname: CsvDataService
    propagate: false
  DatabaseService:
    level: INFO
    handlers: [ console ]
    qualname: DatabaseService
    propagate: false
  DatabaseManagementService:
    level: DEBUG
    handlers: [ console ]
    qualname: DatabaseManagementService
    propagate: false
  ValueAccessor:
    level: WARNING
    handlers: [ console ]
    qualname: ValueAccessor
    propagate: false
  Value:
    level: WARNING
    handlers: [ console ]
    qualname: Value
    propagate: false
  CompetitionProcessor:
    level: INFO
    handlers: [ console ]
    qualname: CompetitionProcessor
    propagate: false
  Analyst:
    level: INFO
    handlers: [ console ]
    qualname: Analyst
    propagate: false
  points_methods.classic_method:
    level: WARNING
    handlers: [ console ]
    qualname: points_methods.classic_method
    propagate: false

  # thirdparty
  matplotlib.font_manager:
    level: WARNING
    handlers: [ console ]
    qualname: matplotlib.font_manager
    propagate: false
